import test from 'node:test';
import assert from 'node:assert/strict';
import express from 'express';
import jwt from 'jsonwebtoken';
import router from '../routes/obsOutput.js';
import ObsOutput from '../models/ObsOutput.js';
import ObsBridge from '../models/ObsBridge.js';
import SportsAdmin from '../models/SportsAdmin.js';
import Tournament from '../models/Tournament.js';
import OverlayState from '../models/OverlayState.js';

test('permanent output copies are stable, switching is explicit, and browser acknowledgements are revision-scoped', async t => {
  const previous = process.env.JWT_SECRET; process.env.JWT_SECRET = 'output-route-test';
  t.after(() => { if (previous === undefined) delete process.env.JWT_SECRET; else process.env.JWT_SECRET = previous; });
  t.mock.method(SportsAdmin, 'findById', async () => ({ active: true }));
  t.mock.method(ObsOutput, 'init', async () => ({}));
  const eventId = '012345678901234567890123';
  let document, active = true, acknowledgement;
  const query = value => ({ select: () => query(value), lean: async () => value });
  t.mock.method(ObsOutput, 'findOneAndUpdate', (filter, update) => {
    if (!document) document = { _id: 'output', tournament: null, revision: 0, seenRevision: -1, seenStateRevision: -1, ...update.$setOnInsert };
    Object.assign(document, update.$set || {});
    document.revision += update.$inc?.revision || 0;
    return query({ ...document });
  });
  t.mock.method(ObsOutput, 'findOne', filter => query(filter.tokenHash === document?.tokenHash ? { ...document } : null));
  t.mock.method(ObsOutput, 'updateOne', async (filter, update) => { acknowledgement = { filter, update }; Object.assign(document, update.$set); if (update.$max) document.seenStateRevision = Math.max(document.seenStateRevision, update.$max.seenStateRevision); });
  t.mock.method(ObsBridge, 'updateOne', async () => ({}));
  t.mock.method(Tournament, 'findById', id => query(String(id) === eventId ? { _id: eventId, name: 'Evento elegido', active } : null));
  t.mock.method(Tournament, 'exists', async () => active);
  t.mock.method(OverlayState, 'findOne', () => query({ revision: 12 }));
  t.mock.method(OverlayState, 'findOneAndUpdate', async () => ({}));
  const app = express(); app.use(express.json()); app.use(router);
  const server = app.listen(0, '127.0.0.1'); await new Promise(resolve => server.once('listening', resolve));
  t.after(() => new Promise(resolve => server.close(resolve)));
  const base = `http://127.0.0.1:${server.address().port}`;
  const headers = { Authorization: `Bearer ${jwt.sign({ sub: eventId }, process.env.JWT_SECRET)}`, 'Content-Type': 'application/json' };
  const call = (path, method = 'GET', body) => fetch(base + path, { method, headers, ...(body ? { body: JSON.stringify(body) } : {}) });
  assert.equal((await fetch(base + '/obs/output')).status, 401);
  const first = await (await call('/obs/output')).json();
  assert.equal(document.tournament, null);
  assert.equal((await (await call('/obs/output')).json()).overlayUrl, first.overlayUrl);
  assert.equal('token' in first, false);
  const token = new URL(first.overlayUrl, base).searchParams.get('token');
  const empty = await fetch(base + '/overlay/output?token=' + token);
  assert.equal(empty.status, 200); assert.equal((await empty.json()).snapshot, null);
  assert.equal((await call('/obs/output/event', 'PUT', { tournamentId: eventId })).status, 200);
  assert.equal(document.tournament, eventId);
  assert.equal((await (await call('/obs/output')).json()).overlayUrl, first.overlayUrl);
  const revision = document.revision;
  await call('/obs/output/event', 'PUT', { tournamentId: eventId });
  assert.equal(document.revision, revision);
  const beat = body => call('/overlay/output/heartbeat?token=' + token, 'POST', body);
  await beat({ outputRevision: revision - 1, tournamentId: eventId, stateRevision: 12 });
  assert.equal(acknowledgement.update.$set.seenRevision, undefined);
  await beat({ outputRevision: revision, tournamentId: eventId, stateRevision: 12 });
  assert.equal(acknowledgement.filter.revision, revision);
  assert.equal((await (await call('/obs/output')).json()).stateConfirmed, true);
  await beat({ outputRevision: revision, tournamentId: eventId, stateRevision: 3 });
  assert.equal(document.seenStateRevision, 12);
  document.lastSeenAt = new Date(Date.now() - 30000);
  assert.equal((await (await call('/obs/output')).json()).stateConfirmed, false);
  active = false;
  assert.equal((await call('/obs/output/event', 'PUT', { tournamentId: eventId })).status, 400);
  assert.equal((await call('/overlay/output/auth?token=' + token, 'POST', { channel_name: 'private-overlay-other', socket_id: '1.1' })).status, 403);
  assert.equal((await call('/obs/output/rotate', 'POST', {})).status, 400);
  const changed = await (await call('/obs/output/rotate', 'POST', { confirmation: 'REEMPLAZAR ENLACE OBS' })).json();
  assert.notEqual(changed.overlayUrl, first.overlayUrl);
  assert.equal((await fetch(base + '/overlay/output?token=' + token)).status, 403);
});
