import test from 'node:test';
import assert from 'node:assert/strict';
import express from 'express';
import jwt from 'jsonwebtoken';
import router from '../routes/sports.js';
import Sponsor from '../models/Sponsor.js';
import SportsAdmin from '../models/SportsAdmin.js';
import Tournament from '../models/Tournament.js';
import OverlayState from '../models/OverlayState.js';
import SportsTeam from '../models/SportsTeam.js';
import SportsPlayer from '../models/SportsPlayer.js';
import SportsMatch from '../models/SportsMatch.js';
import SportsEvent from '../models/SportsEvent.js';

test('shared brands can be created without events and event participation uses a separate endpoint', async t => {
  const previous = process.env.JWT_SECRET;
  process.env.JWT_SECRET = 'local-sponsor-test';
  t.after(() => { if (previous === undefined) delete process.env.JWT_SECRET; else process.env.JWT_SECRET = previous; });
  t.mock.method(SportsAdmin, 'findById', async () => ({ _id: '012345678901234567890123', active: true }));
  let saved;
  t.mock.method(Sponsor.prototype, 'save', async function () { await this.validate(); saved = this.toObject(); return this; });
  t.mock.method(Tournament, 'exists', async () => true);
  const app = express(); app.use(express.json()); app.use(router);
  const server = app.listen(0, '127.0.0.1');
  await new Promise(resolve => server.once('listening', resolve));
  t.after(() => new Promise(resolve => server.close(resolve)));
  const base = `http://127.0.0.1:${server.address().port}`;
  const headers = { Authorization: `Bearer ${jwt.sign({ sub: '012345678901234567890123' }, process.env.JWT_SECRET)}`, 'Content-Type': 'application/json' };
  assert.equal((await fetch(`${base}/sponsors`, { method: 'POST', headers, body: JSON.stringify({ name: 'Marca independiente', confirmed: true }) })).status, 201);
  assert.equal(saved.name, 'Marca independiente');
  assert.equal(saved.tournament, undefined);
  assert.deepEqual(saved.assignments, []);
  assert.equal((await fetch(`${base}/sponsors`, { method: 'POST', headers, body: JSON.stringify({ name: 'Marca', tournament: '012345678901234567890123' }) })).status, 400);
  assert.equal((await fetch(`${base}/tournaments/012345678901234567890123/sponsors`, { method: 'POST', headers, body: JSON.stringify({ sponsorIds: ['invalid'] }) })).status, 400);
  assert.equal((await fetch(`${base}/tournaments/012345678901234567890123/sponsors`, { method: 'POST', body: '{}' })).status, 401);
});

test('event deletion survives overlay failures and preserves shared sponsors', async t => {
  const previous = process.env.JWT_SECRET;
  process.env.JWT_SECRET = 'local-delete-event-test';
  t.after(() => { if (previous === undefined) delete process.env.JWT_SECRET; else process.env.JWT_SECRET = previous; });
  const id = '012345678901234567890123';
  const actions = [];
  t.mock.method(SportsAdmin, 'findById', async () => ({ _id: id, active: true }));
  t.mock.method(Tournament, 'findById', async () => ({ _id: id, name: 'Festival', deleteOne: async () => actions.push('event') }));
  t.mock.method(OverlayState, 'findOneAndUpdate', async () => { throw new Error('Overlay no disponible'); });
  t.mock.method(console, 'warn', () => {});
  const teamUpdates = [];
  t.mock.method(SportsTeam, 'updateMany', async (filter, update) => teamUpdates.push({ filter, update }));
  for (const [Model, name] of [[SportsTeam, 'teams'], [SportsPlayer, 'players'], [SportsMatch, 'matches'], [SportsEvent, 'history'], [OverlayState, 'state']]) t.mock.method(Model, 'deleteMany', async () => actions.push(name));
  const updates = [];
  t.mock.method(Sponsor, 'updateMany', async (filter, update) => updates.push({ filter, update }));
  t.mock.method(Sponsor, 'deleteMany', async () => { throw new Error('Shared brands must be preserved'); });
  const app = express(); app.use(express.json()); app.use(router);
  const server = app.listen(0, '127.0.0.1');
  await new Promise(resolve => server.once('listening', resolve));
  t.after(() => new Promise(resolve => server.close(resolve)));
  const url = `http://127.0.0.1:${server.address().port}/tournaments/${id}`;
  const headers = { Authorization: `Bearer ${jwt.sign({ sub: id }, process.env.JWT_SECRET)}`, 'Content-Type': 'application/json' };
  assert.equal((await fetch(url, { method: 'DELETE', headers, body: JSON.stringify({ confirmation: 'Wrong name' }) })).status, 400);
  assert.deepEqual(actions, []);
  assert.equal((await fetch(url, { method: 'DELETE', headers, body: JSON.stringify({ confirmation: ' Festival ' }) })).status, 204);
  assert.deepEqual(actions, ['history', 'matches', 'state', 'event']);
  assert.equal(teamUpdates.length, 2);
  assert.deepEqual(teamUpdates[1].update, { $pull: { tournaments: id } });
  assert.equal(updates.length, 2);
  assert.deepEqual(updates[1].update, { $pull: { assignments: { tournament: id } } });
});
