import test from 'node:test';
import assert from 'node:assert/strict';
import express from 'express';
import jwt from 'jsonwebtoken';
import router from '../routes/teams.js';
import SportsAdmin from '../models/SportsAdmin.js';
import SportsTeam from '../models/SportsTeam.js';
import SportsMatch from '../models/SportsMatch.js';
import Tournament from '../models/Tournament.js';
import { teamFilter, teamIdentity } from '../services/teamLibrary.js';
test('team identity is automatic and legacy event membership remains readable', () => {
  assert.deepEqual(teamIdentity({ name: 'Juventud San Juan' }), { name: 'Juventud San Juan', shortName: 'Juventud San Juan', code: 'JSJ' });
  assert.equal(teamIdentity({ name: 'Águila' }).code, 'AGU');
  assert.equal(teamIdentity({ name: 'AB' }).code, 'ABX');
  assert.deepEqual(teamFilter('event'), { $or: [{ tournament: 'event' }, { tournaments: 'event' }] });
  const team = new SportsTeam({ ...teamIdentity({ name: 'Equipo libre' }) });
  assert.equal(team.validateSync(), undefined);
});
test('event assignment is reusable, idempotent and cannot remove teams with match history', async t => {
  const previous = process.env.JWT_SECRET; process.env.JWT_SECRET = 'team-library-test';
  t.after(() => { if (previous === undefined) delete process.env.JWT_SECRET; else process.env.JWT_SECRET = previous; });
  const event = '012345678901234567890123', team = 'abcdefabcdefabcdefabcdef';
  t.mock.method(SportsAdmin, 'findById', async () => ({ _id: event, active: true }));
  t.mock.method(Tournament, 'exists', async () => true);
  t.mock.method(SportsTeam, 'countDocuments', async () => 1);
  const updates = [];
  t.mock.method(SportsTeam, 'updateMany', async (filter, update) => updates.push({ filter, update }));
  t.mock.method(SportsTeam, 'updateOne', async (filter, update) => updates.push({ filter, update }));
  t.mock.method(SportsTeam, 'find', filter => ({ sort: async () => [{ _id: team, name: 'Equipo', tournaments: [event] }] }));
  let hasMatch = true;
  t.mock.method(SportsMatch, 'exists', async () => hasMatch);
  const app = express(); app.use(express.json()); app.use(router);
  const server = app.listen(0, '127.0.0.1'); await new Promise(resolve => server.once('listening', resolve));
  t.after(() => new Promise(resolve => server.close(resolve)));
  const base = `http://127.0.0.1:${server.address().port}`;
  const headers = { Authorization: `Bearer ${jwt.sign({ sub: event }, process.env.JWT_SECRET)}`, 'Content-Type': 'application/json' };
  const call = (path, method, body) => fetch(base + path, { method, headers, ...(body ? { body: JSON.stringify(body) } : {}) });
  assert.equal((await fetch(base + '/teams')).status, 401);
  assert.equal((await call('/teams', 'POST', { name: 'Equipo', tournament: event })).status, 400);
  assert.equal((await call(`/tournaments/${event}/teams`, 'POST', { teamIds: [team, team] })).status, 200);
  assert.deepEqual(updates[0].update, { $addToSet: { tournaments: event } });
  assert.equal(updates[0].filter._id.$in.length, 1);
  assert.equal((await call(`/tournaments/${event}/teams/${team}`, 'DELETE')).status, 409);
  assert.equal(updates.length, 1);
  hasMatch = false;
  assert.equal((await call(`/tournaments/${event}/teams/${team}`, 'DELETE')).status, 204);
  assert.deepEqual(updates[1].update, { $pull: { tournaments: event } });
  assert.deepEqual(updates[2].update, { $unset: { tournament: 1 } });
});
